activity_list = [
                 ["TUCASEID", "case_id"],
                 ["TUACTIVITY_N", "activity_n"],
                 ["TRCODE", "activity_code"],
                 # ["TRTIER2P", "activity_code4"],
                 # ["TUSTARTTIM", "start_time"],
                 # ["TUSTOPTIME", "stop_time"],
                 ["TUACTDUR24", "duration"],
                 # ["TRTOHH_LN", "time_in_activity_own_hh_child"],
                 # ["TRTO_LN", "time_in_activity_own_child"],
                 # ["TRTEC_LN", "time_spent_eldercare"],
                ]

activity_fields = []
for k, v in activity_list:
  if k not in ["TUSTARTTIM", "TUSTOPTIME"]: 
    activity_fields.append(v + " INTEGER")
  else: activity_fields.append(v)
activity_pk = ["case_id", "activity_n"]


respondent_list = [
                   ["TUCASEID"     , "case_id"], 
                   ["TULINENO"     , "line_no"], 
                   #["TESPUHRS"     , "spouse_hours_worked"], 
	                 #["TRDTIND1"     , "detailed_industry_class"], 
	                 #["TRDTOCC1"     , "detailed_occupation_code"], 
	                 #["TRERNHLY"     , "hourly_earnings_main_job"], 
	                 #["TRERNUPD"     , "earnings_from_atus"], 
	                 #["TRHERNAL"     , "trernhly_allocation_flag"], 
	                 #["TRHHCHILD"    , "presence_of_hh_children"], 
	                 #["TRIMIND1"     , "main_job_intermediate_industry"], 
	                 #["TRMJIND1"     , "main_job_industry"], 
	                 #["TRMJOCC1"     , "main_job_occupation"], 
	                 #["TRMJOCGR"     , "major_occupation_cat"], 
	                 #["TRNUMHOU"     , "number_in_hh"], 
	                 #["TRNHHCHILD"   , "presence_of_own_nonhh_children"], 
	                 #["TROHHCHILD"   , "presence_of_own_hh_children"], 
	                 #["TRTALONE_WK"  , "daily_time_alone"], 
	                 #["TRTALONE"     , "daily_time_alone_non_work"], 
	                 #["TRTCC"        , "daily_time_secondary_childcare_hh_or_own_childrn"], 
	                 #["TRTHHFAMILY"  , "daily_time_with_hh_family"], 
	                 #["TRTNOCHILD"   , "daily_time_with_nonown_children"], 
	                 #["TRTNOHH"      , "daily_time_secondary_childcare_nonown_hh_children"], 
	                 #["TRTO"         , "daily_time_secondary_childcare_own_children"], 
	                 #["TRTOHH"       , "daily_time_secondary_childcare_own_hh_children"], 
	                 #["TRTOHHCHILD"  , "daily_time_with_own_hh_children"], 
	                 #["TRTONHH"      , "daily_time_secondary_childcare_own_nonhh_children"], 
	                 #["TRTONHHCHILD" , "daily_time_with_own_nonhh_children"], 
	                 #["TRTSPONLY"    , "daily_time_with_spouse_only"],
	                 #["TRTSPOUSE"    , "daily_time_with_spouse"],
	                 #["TRTUNMPART"   , "daily_time_with_unmarried_partner"],
	                 #["TRWERNAL"     , "trernwa_allocation_flag"],
	                 #["TTHR"         , "hourly_pay_topcode_flag"],
	                 #["TTOT"         , "overtime_pay_topcode_flag"],
	                 #["TTWK"         , "weekly_earnings_topcode_flag"],
	                 #["TUABSOT"      , "had_job_past_week"],
	                 #["TUYEAR"       , "year_of_diary_day"],
	                 #["TEABSRSN"     , "why_absent_from_job_last_week"],
	                 #["TEERN"        , "total_weekly_overtime_earnings"],
	                 #["TEERNH1O"     , "hourly_wage_of_main_job"],
	                 #["TEERNH2"      , "TEERNH2"],
	                 #["TEERNHRO"     , "usual_weekly_hours_worked"],
	                 #["TEERNHRY"     , "hourly_status_1_not_2"],
	                 #["TEERNPER"     , "way_earnings_reported"],
	                 #["TEERNRT"      , "paid_at_hourly_rate"],
	                 #["TEERNUOT"     , "usually_receive_overtime_or_tipes"],
	                 #["TEERNWKP"     , "weeks_per_year_paid"],
	                 #["TEHRFTPT"     , "works_30plus_hours_family_business"],
	                 #["TEHRUSL1"     , "usual_hours_worked_main_job"],
	                 #["TEHRUSL2"     , "usual_hours_worked_other_jobs"],
	                 #["TEIO1COW"     , "class_of_worker"],
	                 #["TEIO1ICD"     , "industry_code"],
	                 #["TEIO1OCD"     , "occupation_code"],
	                 #["TELAYAVL"     , "TELAYAVL"],
	                 #["TELAYLK"      , "looking_for_work"],
	                 #["TELKAVL"      , "could_have_started_job_last_week_if_offered"],
	                 #["TELKM1"       , "ways_sought_job"],
	                 #["TERET1"       , "wants_job"],
	                 #["TESCHFT"      , "enrolled_as_ft_student"],
	                 #["TUBUS"        , "hh_member_owns_business"],
	                 #["TUBUS1"       , "has_worked_unpaid_family_business"],
	                 #["TUBUS2OT"     , "receive_profits_from_family_business"],
	                 #["TUBUSL1"      , "line_no_of_business_owner"],
	                 #["TUBUSL2"      , "line_no_of_business_2nd_owner"],
	                 #["TUBUSL3"      , "line_no_of_business_3rd_owner"],
	                 #["TUBUSL4"      , "line_no_of_business_4th_owner"],
	                 #["TUCC2"        , "time_first_hh_child_woke_up"],
	                 #["TUCC4"        , "time_last_hh_child_went_to_bed"],
	                 #["TUFWK"        , "has_worked_past_week"],
	                 #["TUIO1MFG"     , "type_of_work"],
	                 #["TUIODP1"      , "still_at_cps_job"],
	                 #["TUIODP2"      , "same_work_at_cps_job"],
	                 #["TUIODP3"      , "work_descr_from_cps_accurate"],
	                 #["TULAY"        , "laid_off_past_week"],
	                 #["TULAY6M"      , "expect_recall_6m"],
	                 #["TULAYAVR"     , "reason_could_not_start_job"],
	                 #["TULAYDT"      , "given_date_to_return_to_work"],
	                 #["TULK"         , "has_sought_work"],
	                 #["TULKAVR"      , "reason_unable_to_work"],
	                 #["TULKDK1"      , "ways_sought_work_1"],
	                 #["TULKDK2"      , "ways_sought_work_2"],
	                 #["TULKDK3"      , "ways_sought_work_3"],
	                 #["TULKDK4"      , "ways_sought_work_4"],
	                 #["TULKM2"       , "ways_sought_work_4weeks"],
	                 #["TULKM3"       , "ways_sought_work_4weeks_3"],
	                 #["TULKM4"       , "ways_sought_work_4weeks_4"],
	                 #["TULKM5"       , "ways_sought_work_4weeks_5"],
	                 #["TULKM6"       , "ways_sought_work_4weeks_6"],
	                 #["TULKPS1"    , "TULKPS1"],
	                 #["TULKPS2"    , "TULKPS2"],
	                 #["TULKPS3"    , "TULKPS3"],
	                 #["TULKPS4"    , "TULKPS4"],
	                 #["TUMONTH"      , "month_of_diary"],
	                 #["TRTCCC"       , "nonwork_time_spent_with_customers"],
	                 #["TRTCCTOT"     , "daily_time_secondary_childcare_all"],
	                 #["TRTCHILD"     , "daily_time_with_children"],
	                 #["TRTCOC"       , "daily_time_secondary_childcare_no_nhh_children"],
	                 #["TRTFAMILY"    , "daily_time_with_family"],
	                 #["TRTFRIEND"    , "daily_time_with_friends"],
	                 #["TRTHH"        , "daily_time_secondary_childcare_hh_children"],
	                 #["TUDIS2"       , "disability_prevents_work"],
	                 #["TURETOT"      , "retired"],
	                 #["TUSPABS"      , "spouse_had_job_last_week"],
	                 #["TUSPUSFT"     , "spouse_works_full_time"],
	                 #["TUSPWK"       , "spouse_worked_last_week"],
	                 #["TREMODR"      , "eating_module_respondent"],
	                 #["TUCC9"        , "related_to_no_nonhh_children"],
	                 #["TUDIARYDATE"  , "diary_date"],
	                 #["TUDIS"        , "still_has_cps_disability"],
	                 #["TUDIS1"       , "disability_precludes_work"],
	                 ["TRCHILDNUM"   , "number_of_hh_children"],
	                 #["TUDIARYDAY"   , "dow_of_diary_day"],
	                 #["TRERNWA"      , "weekly_earnings_main_job"],
	                 #["TRHOLIDAY"    , "diary_day_holiday"],
	                 #["TRSPFTPT"     , "partner_employment_status"],
	                 #["TRSPPRES"     , "spouse_or_partner_present"],
	                 #["TRDPFTPT"     , "full_time_part_time"],
	                 #["TUFNWGTP"     , "final_weight"],
	                 #["TESPEMPNOT"   , "spouse_or_partner_employment_status"],
	                 #["TESCHLVL"     , "student_in_hs_or_univ"],
	                 #["TESCHENR"     , "enrolled_in_school"],
	                 #["TEMJOT"       , "worked_more_than_one_job"],
	                 #["TELFS"        , "edited_labor_force_status"],
	                 #["TEHRUSLT"     , "total_usual_hours_worked"],
	                 #["TRYHHCHILD"   , "age_of_youngest_hh_child"],
	                 #["TRWBMODR"     , "TRWBMODR"],
	                 #["TRTCCC_WK"    , "total_time_with_customers"], 
	                 #["TRLVMODR"     , "TRLVMODR"],
	                 #["TRTEC"        , "total_time_eldercare"],
	                 #["TUECYTD"      , "eldercare_yesterday"],
	                 #["TUELDER"      , "any_eldercare_in_month"],
	                 #["TUELFREQ"     , "frequency_of_eldercare"],
	                 #["TUELNUM"      , "eldercare_how_many"],
                  ]

respondent_fields = []
for k, v in respondent_list:
  if k not in ["TUFNWGTP"]: respondent_fields.append(v + " INTEGER")
  else: respondent_fields.append(v + " FLOAT")
respondent_pk = ["case_id", "line_no"]

  

roster_list = [["TUCASEID" , "case_id"], 
	             ["TULINENO" , "line_no"], 
	             ["TERRP"    , "how_related"], 
	             ["TEAGE"    , "edited_age"], 
	             ["TESEX"    , "edited_sex"],
              ]

roster_fields = [v + " INTEGER" for k, v in roster_list]
roster_pk = ["case_id", "line_no"]


cps_list = [["TUCASEID", "case_id"], 
            ["TULINENO", "line_no"],  
            # ["PTDTRACE", "race"],
            # ["PEHSPNON", "hispanic_origin"],
            ["HEFAMINC", "family_income"],
            ["PEEDUCA", "educational_attainment"], 
            ["PEMS123", "duration_of_masters"],
            ["PECYC", "years_in_college"],
            ["PEMARITL", "marital_status"], 
            ["GESTFIPS", "state_code"],
            # ["GTMETSTA", "metsta_code"],
            # ["GEREG", "region"]
            ]

cps_fields = [v + " INTEGER" for k, v in cps_list]
cps_pk = ["case_id", "line_no"]
